[package]
name = "advent2019"
version = "6.2.0"
authors = ["Romain Delamare <romain@delama.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "14.0.0"
